version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD= 1234
      - MARIADB_DATABASE= pokemon
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build:
      context: ./API_POKEMON
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:5000"
    depends_on:
      - mariadb

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mariadb_data: